POSTGRES:
  USER: "postgres"
  PASSWORD: "postgres"
  HOST: "postgres" 
  PORT: "5432"
  DATABASE_NAME: "rag_db"
  SQLALCHEMY_ECHO: "true"

MYSQL:
  HOST: "107.148.233.40"
  PORT: 15479
  DATABASE: "dev_finance_system"
  USER: "finance_working"
  PASSWORD: "eD2WgK90HTpQkcllmMwdKHfIbitzohq0"
  CHARSET: "utf8mb4"
  POOL_SIZE: 10
  MAX_OVERFLOW: 20

# Config connect db at local
# POSTGRES:
#   USER: "postgres"
#   PASSWORD: "123456"
#   HOST: "localhost" 
#   PORT: "5432"
#   DATABASE_NAME: "rag"
#   SQLALCHEMY_ECHO: "true"