POSTGRES:
  USER: ""
  PASSWORD: ""
  HOST: "" 
  PORT: ""
  DATABASE_NAME: ""
  SQLALCHEMY_ECHO: "true"

MYSQL:
  HOST: ""
  PORT: 15479
  DATABASE: ""
  USER: ""
  PASSWORD: ""
  CHARSET: ""
  POOL_SIZE: 10
  MAX_OVERFLOW: 20
